marco = Player.create!(name: "Marco", hp: 150, strength: 50)
marco.images << Image.create(source: "uploads/player/marco.png")
marco.images << Image.create(source: "uploads/player/marcoSelect.png")
marco.actions << Action.create!(name: "FuckOff", damage: 80)
marco.actions << Action.create!(name: "I'm Correct", damage: 70)

dania = Player.create!(name: "Dania", hp: 70, strength: 130)
dania.images << Image.create(source: "uploads/player/dania.gif")
dania.images << Image.create(source: "uploads/player/daniaSelect.gif")
dania.actions << Action.create!(name: "CSS powers", damage: 170)
dania.actions << Action.create!(name: "Being cute as Tiny Friend", damage: 120 )

tabish = Player.create!(name: "Tabish", hp: 80, strength: 120)
tabish.images << Image.create(source: "uploads/player/tabish.jpg")
tabish.images << Image.create(source: "uploads/player/tabishSelect.jpg")
tabish.actions << Action.create!(name: "Smash", damage: 140)
tabish.actions << Action.create!(name: "Competitive strike", damage: 100)

cristhian = Player.create!(name: "Cristhian", hp: 140, strength: 60)
cristhian.images << Image.create(source: "uploads/player/cristhian.jpg")
cristhian.images << Image.create(source: "uploads/player/cristhianSelect.jpg")
cristhian.actions << Action.create!(name: "Sing", damage: 140)
cristhian.actions << Action.create!(name: "MerengueOff", damage: 90)

lewis = Player.create!(name: "Lewis", hp: 80, strength: 120)
lewis.images << Image.create(source: "uploads/player/lewis.jpg")
lewis.images << Image.create(source: "uploads/player/lewisSelect.jpg")
lewis.actions << Action.create!(name: "BackHandSpin", damage: 140)
lewis.actions << Action.create!(name: "Flounder", damage: 50)

oleg = Player.create!(name: "Oleg", hp: 75, strength: 125)
oleg.images << Image.create(source: "uploads/player/oleg.jpg")
oleg.images << Image.create(source: "uploads/player/olegSelect.jpg")
oleg.actions << Action.create!(name: "TopSpin", damage: 140)
oleg.actions << Action.create!(name: "Osundo disguise", damage: 50)

ActionPicture.create(image: "uploads/actions/aiiiii.png")
ActionPicture.create(image: "uploads/actions/brapbrap.png")
ActionPicture.create(image: "uploads/actions/burn!.png")
ActionPicture.create(image: "uploads/actions/codamn.png")
ActionPicture.create(image: "uploads/actions/kablam!.png")
ActionPicture.create(image: "uploads/actions/oooooh.png")
ActionPicture.create(image: "uploads/actions/pow.png")
ActionPicture.create(image: "uploads/actions/smash.png")
